services:
  nginx:
    image: nginx:latest
    restart: "unless-stopped"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app

  php:
    build:
      context: ./php
      dockerfile: php.Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    volumes:
      - ./:/app
    working_dir: /app
    networks:
      - app
      - mm23_freqtrade

  cron:
    build:
      context: ./cron
      dockerfile: cron.Dockerfile
      args:
        CRON_MINUTES: ${CRON_MINUTES}
    restart: "unless-stopped"
    networks:
      - app
      - mm23_freqtrade

  mongo:
    image: mongo
    container_name: mongodb
    restart: "unless-stopped"
    networks:
      - app
    user: "${UID}:${GID}"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASS}

networks:
  app:
    driver: bridge

  mm23_freqtrade:
    driver: overlay
    external: true
